dist: xenial

language: python

python: 3.6

cache: pip

install:
  # Install Python script dependencies
  - pip install --upgrade pip setuptools
  - pip install --upgrade -r requirements.txt

  # Install Python linter
  - pip install --upgrade flake8

  # Install Python testing and coverage
  - pip install --upgrade pytest pytest-cov

before_script:
  # Run Python linter
  - flake8 --max-line-length=100 src/ test/

script:
  # Run tests and coverage report
  - python -m pytest -v --cov-report=term-missing --cov-fail-under=99 --cov=src/

deploy:
  provider: bluemixcloudfoundry
  username: apikey
  password: $IBMCLOUD_API_KEY
  organization: rneumann@br.ibm.com
  space: dev
  manifest: manifest.yml
  region: ng
  api: https://api.ng.bluemix.net
  on:
    branch:
      - external

notifications:
  slack: cloud-iot-ufrj:sXcQdHCksbSxrPLgmQTu5xSZ
