dist: trusty

group: bluezone

language: python

python:
    - "3.6"

cache: pip

install:
  # Install Python script dependencies
  - pip install --quiet --upgrade pip setuptools
  - pip install --quiet --upgrade -r requirements.txt

before_script:
  # Run Python linter
  - pip install --quiet --upgrade flake8
  - flake8 --max-line-length=100 src/ test/

script:
  # Run tests and coverage
  - pip install --quiet --upgrade pytest pytest-cov
  - python -m pytest -v --cov-report=term-missing --cov-fail-under=80 --cov=src/modules/

deploy:
  provider: bluemixcloudfoundry
  username: apikey
  password: $IBMCLOUD_API_KEY
  organization: rneumann@br.ibm.com
  space: dev
  manifest: manifest.yml
  region: ng
  api: https://api.ng.bluemix.net
  on:
    branch:
      - master

notifications:
  slack: ibm-research:gsBidsvzx4efe07iBit0931m
