dist: trusty

group: bluezone

language: python

python:
    - "3.6"

cache: pip

install:
  # Install Python script dependencies
  - pip install --quiet --upgrade pip setuptools
  - pip install --quiet --upgrade -r requirements.txt

  # Install Python linter
  - pip install --quiet --upgrade flake8

  # Install Python testing and coverage
  - pip install --quiet --upgrade pytest coverage

before_script:
  # Run Python linter
  - flake8 --max-line-length=100 src/ test/

script:
  # Run tests
  - python -m pytest -v

  # Run test coverage
  - coverage report --show-missing --fail-under=99 --include=src/*

deploy:
  provider: bluemixcloudfoundry
  username: apikey
  password: $IBMCLOUD_API_KEY
  organization: rneumann@br.ibm.com
  space: dev
  manifest: manifest.yml
  region: ng
  api: https://api.ng.bluemix.net
  on:
    branch:
      - master

notifications:
  slack: ibm-research:gsBidsvzx4efe07iBit0931m
